name = "acquit-web"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./apps/web/dist"

[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://othxichdhzdxgtatautb.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_3GfWfA2a1RIjnBzXVUM6qg_8z7eh-pv"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_3GfWfA2a1RIjnBzXVUM6qg_8z7eh-pv"
VITE_SUPABASE_URL = "https://othxichdhzdxgtatautb.supabase.co"
VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_3GfWfA2a1RIjnBzXVUM6qg_8z7eh-pv"
NODE_ENV = "production"

[env.preview.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://othxichdhzdxgtatautb.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_3GfWfA2a1RIjnBzXVUM6qg_8z7eh-pv"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_3GfWfA2a1RIjnBzXVUM6qg_8z7eh-pv"
VITE_SUPABASE_URL = "https://othxichdhzdxgtatautb.supabase.co"
VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_3GfWfA2a1RIjnBzXVUM6qg_8z7eh-pv"
NODE_ENV = "preview"
