// This file is auto-generated by mockupPreviewPlugin.ts.
// Clean dual import graph - direct imports for Next.js compatibility
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/acquit-case-workspace/AILab.tsx": () => import("../components/mockups/acquit-case-workspace/AILab.tsx"),
  "./components/mockups/acquit-case-workspace/AcquitAcademy.tsx": () => import("../components/mockups/acquit-case-workspace/AcquitAcademy.tsx"),
  "./components/mockups/acquit-case-workspace/AttorneyDirectory.tsx": () => import("../components/mockups/acquit-case-workspace/AttorneyDirectory.tsx"),
  "./components/mockups/acquit-case-workspace/CaseTimeline.tsx": () => import("../components/mockups/acquit-case-workspace/CaseTimeline.tsx"),
  "./components/mockups/acquit-case-workspace/CaseWorkspace.tsx": () => import("../components/mockups/acquit-case-workspace/CaseWorkspace.tsx"),
  "./components/mockups/acquit-case-workspace/DocumentEditorVSCode.tsx": () => import("../components/mockups/acquit-case-workspace/DocumentEditorVSCode.tsx"),
  "./components/mockups/acquit-case-workspace/EvidenceCarousel.tsx": () => import("../components/mockups/acquit-case-workspace/EvidenceCarousel.tsx"),
  "./components/mockups/acquit-case-workspace/FeaturedAttorneysCarousel.tsx": () => import("../components/mockups/acquit-case-workspace/FeaturedAttorneysCarousel.tsx"),
  "./components/mockups/acquit-case-workspace/FeaturedCoursesCarousel.tsx": () => import("../components/mockups/acquit-case-workspace/FeaturedCoursesCarousel.tsx"),
  "./components/mockups/acquit-case-workspace/FilingCenter.tsx": () => import("../components/mockups/acquit-case-workspace/FilingCenter.tsx"),
  "./components/mockups/acquit-case-workspace/GoogleWorkspaceIntegration.tsx": () => import("../components/mockups/acquit-case-workspace/GoogleWorkspaceIntegration.tsx"),
  "./components/mockups/acquit-case-workspace/LawLibraryExplorer.tsx": () => import("../components/mockups/acquit-case-workspace/LawLibraryExplorer.tsx"),
  "./components/mockups/acquit-case-workspace/RagCitationViewer.tsx": () => import("../components/mockups/acquit-case-workspace/RagCitationViewer.tsx"),
  "./components/mockups/acquit-case-workspace/SovereignCylinder.tsx": () => import("../components/mockups/acquit-case-workspace/SovereignCylinder.tsx"),
  "./components/mockups/acquit-case-workspace/StitchGallery.tsx": () => import("../components/mockups/acquit-case-workspace/StitchGallery.tsx"),
  "./components/mockups/chain-of-command/ChainOfCommandWorkspace.tsx": () => import("../components/mockups/chain-of-command/ChainOfCommandWorkspace.tsx")
};

// Direct module exports for cleaner import resolution
export const directExports = {
  AILab: () => import("../components/mockups/acquit-case-workspace/AILab.tsx"),
  AcquitAcademy: () => import("../components/mockups/acquit-case-workspace/AcquitAcademy.tsx"),
  AttorneyDirectory: () => import("../components/mockups/acquit-case-workspace/AttorneyDirectory.tsx"),
  CaseTimeline: () => import("../components/mockups/acquit-case-workspace/CaseTimeline.tsx"),
  CaseWorkspace: () => import("../components/mockups/acquit-case-workspace/CaseWorkspace.tsx"),
  DocumentEditorVSCode: () => import("../components/mockups/acquit-case-workspace/DocumentEditorVSCode.tsx"),
  EvidenceCarousel: () => import("../components/mockups/acquit-case-workspace/EvidenceCarousel.tsx"),
  FeaturedAttorneysCarousel: () => import("../components/mockups/acquit-case-workspace/FeaturedAttorneysCarousel.tsx"),
  FeaturedCoursesCarousel: () => import("../components/mockups/acquit-case-workspace/FeaturedCoursesCarousel.tsx"),
  FilingCenter: () => import("../components/mockups/acquit-case-workspace/FilingCenter.tsx"),
  GoogleWorkspaceIntegration: () => import("../components/mockups/acquit-case-workspace/GoogleWorkspaceIntegration.tsx"),
  LawLibraryExplorer: () => import("../components/mockups/acquit-case-workspace/LawLibraryExplorer.tsx"),
  RagCitationViewer: () => import("../components/mockups/acquit-case-workspace/RagCitationViewer.tsx"),
  SovereignCylinder: () => import("../components/mockups/acquit-case-workspace/SovereignCylinder.tsx"),
  StitchGallery: () => import("../components/mockups/acquit-case-workspace/StitchGallery.tsx"),
  ChainOfCommandWorkspace: () => import("../components/mockups/chain-of-command/ChainOfCommandWorkspace.tsx")
};
