// AUTO-GENERATED by scripts/convert-stitch-to-react.mjs -- do not edit.
import type { ComponentType } from "react";
import AccessibilitySettings from "./pages/accessibility_settings";
import AcquitAiGenteamAiWorkspaceLemonadeServer from "./pages/acquit.ai_genteam_ai_workspace_lemonade_server";
import AcquitAiGenteamMultiAgentAutonomousWorkspaceTelegramLemonade from "./pages/acquit.ai_genteam_multi_agent_autonomous_workspace_telegram_lemonade";
import AcquitAiTelegramGenteamAiWorkspaceLemonadeServer from "./pages/acquit.ai_telegram_genteam_ai_workspace_lemonade_server";
import AiEngineModelsAgentPersonasPlaygroundStudio from "./pages/ai_engine_models_agent_personas_playground_studio";
import AiEngineSettings from "./pages/ai_engine_settings";
import CaseTimelineChronology1 from "./pages/case_timeline_chronology_1";
import CaseTimelineChronology2 from "./pages/case_timeline_chronology_2";
import CaseTimelineEventRecord from "./pages/case_timeline_event_record";
import CaseTimelineLogEvent from "./pages/case_timeline_log_event";
import ChambersAiLegalTeam1 from "./pages/chambers_ai_legal_team_1";
import ChambersAiLegalTeam2 from "./pages/chambers_ai_legal_team_2";
import ChambersAppointCounsel from "./pages/chambers_appoint_counsel";
import ChambersConferenceRoom1 from "./pages/chambers_conference_room_1";
import ChambersConferenceRoom2 from "./pages/chambers_conference_room_2";
import ChambersCounselBrief from "./pages/chambers_counsel_brief";
import ChambersFullBenchView from "./pages/chambers_full_bench_view";
import ChambersMitigationMemo from "./pages/chambers_mitigation_memo";
import ChambersPleaAnalysis from "./pages/chambers_plea_analysis";
import ChambersRightsAudit from "./pages/chambers_rights_audit";
import ChambersSessionTranscripts from "./pages/chambers_session_transcripts";
import CommandCenterDashboard1 from "./pages/command_center_dashboard_1";
import CommandCenterDashboard2 from "./pages/command_center_dashboard_2";
import CommandCenterFullNavigationalHub from "./pages/command_center_full_navigational_hub";
import CommandCenterGenteamWorkspace1 from "./pages/command_center_genteam_workspace_1";
import CommandCenterGenteamWorkspace2 from "./pages/command_center_genteam_workspace_2";
import CommandCenterHome from "./pages/command_center_home";
import CommandCenterInteractiveNavigationalHub from "./pages/command_center_interactive_navigational_hub";
import CommandCenterNavigationalHub from "./pages/command_center_navigational_hub";
import CommandCenterRefinedSocialHub1 from "./pages/command_center_refined_social_hub_1";
import CommandCenterRefinedSocialHub2 from "./pages/command_center_refined_social_hub_2";
import CommandCenterSocialLegalHub from "./pages/command_center_social_legal_hub";
import CommandCenterSocialNewsHub from "./pages/command_center_social_news_hub";
import CommandCenterTelegramLegalHub from "./pages/command_center_telegram_legal_hub";
import CounselDirectoryAttorneyProfile from "./pages/counsel_directory_attorney_profile";
import CounselDirectoryCounselListings from "./pages/counsel_directory_counsel_listings";
import CounselDirectoryProBonoLegalAid from "./pages/counsel_directory_pro_bono_legal_aid";
import CounselDirectorySearch from "./pages/counsel_directory_search";
import CounselDirectorySearchPortal1 from "./pages/counsel_directory_search_portal_1";
import CounselDirectorySearchPortal2 from "./pages/counsel_directory_search_portal_2";
import CourtWatchDocketActivity from "./pages/court_watch_docket_activity";
import CourtWatchHearingPrepKit from "./pages/court_watch_hearing_prep_kit";
import FilingCenterCourtSubmission from "./pages/filing_center_court_submission";
import GenteamAutonomousSparringDebateMarcusSterlingVsAusaVance from "./pages/genteam_autonomous_sparring_debate_marcus_sterling_vs_ausa_vance";
import HearingPrepWarRoom from "./pages/hearing_prep_war_room";
import HelpOnboarding from "./pages/help_onboarding";
import IntegrationsSettings from "./pages/integrations_settings";
import InvestigationsActiveResearch1 from "./pages/investigations_active_research_1";
import InvestigationsActiveResearch2 from "./pages/investigations_active_research_2";
import InvestigationsEvidenceAnalysis1 from "./pages/investigations_evidence_analysis_1";
import InvestigationsEvidenceAnalysis2 from "./pages/investigations_evidence_analysis_2";
import InvestigationsEvidenceLocker1 from "./pages/investigations_evidence_locker_1";
import InvestigationsEvidenceLocker2 from "./pages/investigations_evidence_locker_2";
import InvestigationsExhibitAnalysis from "./pages/investigations_exhibit_analysis";
import InvestigationsIssueSpotter from "./pages/investigations_issue_spotter";
import InvestigationsResearchMemo from "./pages/investigations_research_memo";
import LawLibraryCaseFolders from "./pages/law_library_case_folders";
import LawLibraryCitationWeb from "./pages/law_library_citation_web";
import LawLibraryPriorResearch from "./pages/law_library_prior_research";
import LawLibraryResearch1 from "./pages/law_library_research_1";
import LawLibraryResearch2 from "./pages/law_library_research_2";
import LawLibrarySearchTheStacks1 from "./pages/law_library_search_the_stacks_1";
import LawLibrarySearchTheStacks2 from "./pages/law_library_search_the_stacks_2";
import LegalOsPrototype from "./pages/legal_os_prototype";
import MotionsTasksCourtCalendar from "./pages/motions_tasks_court_calendar";
import MotionsTasksMotionBoard from "./pages/motions_tasks_motion_board";
import RecordRoomDocuments1 from "./pages/record_room_documents_1";
import RecordRoomDocuments2 from "./pages/record_room_documents_2";
import RecordRoomDraftDesk from "./pages/record_room_draft_desk";
import RecordRoomExhibitGallery from "./pages/record_room_exhibit_gallery";
import RecordRoomFileARecord from "./pages/record_room_file_a_record";
import RecordRoomRecordPreview from "./pages/record_room_record_preview";
import SystemAudit from "./pages/system_audit";
import TheClerkNotificationSettings from "./pages/the_clerk_notification_settings";
import TheDocketCases1 from "./pages/the_docket_cases_1";
import TheDocketCases2 from "./pages/the_docket_cases_2";
import TheDocketClosedMatters from "./pages/the_docket_closed_matters";
import TheDocketOpenAMatter from "./pages/the_docket_open_a_matter";
import TheDocketRetrieveFromCourt from "./pages/the_docket_retrieve_from_court";
import ThreeJs1 from "./pages/three.js_1";
import ThreeJs2 from "./pages/three.js_2";
import UserProfile from "./pages/user_profile";
import WorkspaceSecurity from "./pages/workspace_security";

export const stitchComponents: Record<string, ComponentType> = {
  "accessibility_settings": AccessibilitySettings,
  "acquit.ai_genteam_ai_workspace_lemonade_server": AcquitAiGenteamAiWorkspaceLemonadeServer,
  "acquit.ai_genteam_multi_agent_autonomous_workspace_telegram_lemonade": AcquitAiGenteamMultiAgentAutonomousWorkspaceTelegramLemonade,
  "acquit.ai_telegram_genteam_ai_workspace_lemonade_server": AcquitAiTelegramGenteamAiWorkspaceLemonadeServer,
  "ai_engine_models_agent_personas_playground_studio": AiEngineModelsAgentPersonasPlaygroundStudio,
  "ai_engine_settings": AiEngineSettings,
  "case_timeline_chronology_1": CaseTimelineChronology1,
  "case_timeline_chronology_2": CaseTimelineChronology2,
  "case_timeline_event_record": CaseTimelineEventRecord,
  "case_timeline_log_event": CaseTimelineLogEvent,
  "chambers_ai_legal_team_1": ChambersAiLegalTeam1,
  "chambers_ai_legal_team_2": ChambersAiLegalTeam2,
  "chambers_appoint_counsel": ChambersAppointCounsel,
  "chambers_conference_room_1": ChambersConferenceRoom1,
  "chambers_conference_room_2": ChambersConferenceRoom2,
  "chambers_counsel_brief": ChambersCounselBrief,
  "chambers_full_bench_view": ChambersFullBenchView,
  "chambers_mitigation_memo": ChambersMitigationMemo,
  "chambers_plea_analysis": ChambersPleaAnalysis,
  "chambers_rights_audit": ChambersRightsAudit,
  "chambers_session_transcripts": ChambersSessionTranscripts,
  "command_center_dashboard_1": CommandCenterDashboard1,
  "command_center_dashboard_2": CommandCenterDashboard2,
  "command_center_full_navigational_hub": CommandCenterFullNavigationalHub,
  "command_center_genteam_workspace_1": CommandCenterGenteamWorkspace1,
  "command_center_genteam_workspace_2": CommandCenterGenteamWorkspace2,
  "command_center_home": CommandCenterHome,
  "command_center_interactive_navigational_hub": CommandCenterInteractiveNavigationalHub,
  "command_center_navigational_hub": CommandCenterNavigationalHub,
  "command_center_refined_social_hub_1": CommandCenterRefinedSocialHub1,
  "command_center_refined_social_hub_2": CommandCenterRefinedSocialHub2,
  "command_center_social_legal_hub": CommandCenterSocialLegalHub,
  "command_center_social_news_hub": CommandCenterSocialNewsHub,
  "command_center_telegram_legal_hub": CommandCenterTelegramLegalHub,
  "counsel_directory_attorney_profile": CounselDirectoryAttorneyProfile,
  "counsel_directory_counsel_listings": CounselDirectoryCounselListings,
  "counsel_directory_pro_bono_legal_aid": CounselDirectoryProBonoLegalAid,
  "counsel_directory_search": CounselDirectorySearch,
  "counsel_directory_search_portal_1": CounselDirectorySearchPortal1,
  "counsel_directory_search_portal_2": CounselDirectorySearchPortal2,
  "court_watch_docket_activity": CourtWatchDocketActivity,
  "court_watch_hearing_prep_kit": CourtWatchHearingPrepKit,
  "filing_center_court_submission": FilingCenterCourtSubmission,
  "genteam_autonomous_sparring_debate_marcus_sterling_vs_ausa_vance": GenteamAutonomousSparringDebateMarcusSterlingVsAusaVance,
  "hearing_prep_war_room": HearingPrepWarRoom,
  "help_onboarding": HelpOnboarding,
  "integrations_settings": IntegrationsSettings,
  "investigations_active_research_1": InvestigationsActiveResearch1,
  "investigations_active_research_2": InvestigationsActiveResearch2,
  "investigations_evidence_analysis_1": InvestigationsEvidenceAnalysis1,
  "investigations_evidence_analysis_2": InvestigationsEvidenceAnalysis2,
  "investigations_evidence_locker_1": InvestigationsEvidenceLocker1,
  "investigations_evidence_locker_2": InvestigationsEvidenceLocker2,
  "investigations_exhibit_analysis": InvestigationsExhibitAnalysis,
  "investigations_issue_spotter": InvestigationsIssueSpotter,
  "investigations_research_memo": InvestigationsResearchMemo,
  "law_library_case_folders": LawLibraryCaseFolders,
  "law_library_citation_web": LawLibraryCitationWeb,
  "law_library_prior_research": LawLibraryPriorResearch,
  "law_library_research_1": LawLibraryResearch1,
  "law_library_research_2": LawLibraryResearch2,
  "law_library_search_the_stacks_1": LawLibrarySearchTheStacks1,
  "law_library_search_the_stacks_2": LawLibrarySearchTheStacks2,
  "legal_os_prototype": LegalOsPrototype,
  "motions_tasks_court_calendar": MotionsTasksCourtCalendar,
  "motions_tasks_motion_board": MotionsTasksMotionBoard,
  "record_room_documents_1": RecordRoomDocuments1,
  "record_room_documents_2": RecordRoomDocuments2,
  "record_room_draft_desk": RecordRoomDraftDesk,
  "record_room_exhibit_gallery": RecordRoomExhibitGallery,
  "record_room_file_a_record": RecordRoomFileARecord,
  "record_room_record_preview": RecordRoomRecordPreview,
  "system_audit": SystemAudit,
  "the_clerk_notification_settings": TheClerkNotificationSettings,
  "the_docket_cases_1": TheDocketCases1,
  "the_docket_cases_2": TheDocketCases2,
  "the_docket_closed_matters": TheDocketClosedMatters,
  "the_docket_open_a_matter": TheDocketOpenAMatter,
  "the_docket_retrieve_from_court": TheDocketRetrieveFromCourt,
  "three.js_1": ThreeJs1,
  "three.js_2": ThreeJs2,
  "user_profile": UserProfile,
  "workspace_security": WorkspaceSecurity,
};

export function getStitchComponent(name?: string | null): ComponentType | null {
  if (!name) return null;
  return stitchComponents[name] ?? null;
}
