// AUTO-GENERATED by scripts/convert-stitch-to-react.mjs -- do not edit.
// This placeholder keeps the app building before the first conversion run.
// Run "npm run stitch:convert" to generate the real component registry.
import type { ComponentType } from "react";

export const stitchComponents: Record<string, ComponentType> = {};

export function getStitchComponent(name?: string | null): ComponentType | null {
  if (!name) return null;
  return stitchComponents[name] ?? null;
}
