// This file is auto-generated by gen-mockup-map.mjs.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;

export const modules: ModuleMap = {
  "./components/mockups/acquit-case-workspace/AILab.tsx": () => import("../components/mockups/acquit-case-workspace/AILab.tsx"),
  "./components/mockups/acquit-case-workspace/AcquitAcademy.tsx": () => import("../components/mockups/acquit-case-workspace/AcquitAcademy.tsx"),
  "./components/mockups/acquit-case-workspace/AttorneyDirectory.tsx": () => import("../components/mockups/acquit-case-workspace/AttorneyDirectory.tsx"),
  "./components/mockups/acquit-case-workspace/CaseTimeline.tsx": () => import("../components/mockups/acquit-case-workspace/CaseTimeline.tsx"),
  "./components/mockups/acquit-case-workspace/CaseWorkspace.tsx": () => import("../components/mockups/acquit-case-workspace/CaseWorkspace.tsx"),
  "./components/mockups/acquit-case-workspace/DocumentEditorVSCode.tsx": () => import("../components/mockups/acquit-case-workspace/DocumentEditorVSCode.tsx"),
  "./components/mockups/acquit-case-workspace/EvidenceCarousel.tsx": () => import("../components/mockups/acquit-case-workspace/EvidenceCarousel.tsx"),
  "./components/mockups/acquit-case-workspace/FilingCenter.tsx": () => import("../components/mockups/acquit-case-workspace/FilingCenter.tsx"),
  "./components/mockups/acquit-case-workspace/GoogleWorkspaceIntegration.tsx": () => import("../components/mockups/acquit-case-workspace/GoogleWorkspaceIntegration.tsx"),
  "./components/mockups/acquit-case-workspace/LawLibraryExplorer.tsx": () => import("../components/mockups/acquit-case-workspace/LawLibraryExplorer.tsx"),
  "./components/mockups/acquit-case-workspace/RagCitationViewer.tsx": () => import("../components/mockups/acquit-case-workspace/RagCitationViewer.tsx"),
  "./components/mockups/acquit-case-workspace/SovereignCylinder.tsx": () => import("../components/mockups/acquit-case-workspace/SovereignCylinder.tsx")
};
